services:
  ubuntu:
    build:
      dockerfile: Dockerfile
      args:
        USER_NAME: $USER_NAME
        USER_UID: $USER_UID
        USER_GID: $USER_GID
        USER_PASSWORD: $USER_PASSWORD
        VNC_PASSWORD: $VNC_PASSWORD
        SSH_AUTHORIZED_KEY: $SSH_AUTHORIZED_KEY
        X_GEOMETRY: $X_GEOMETRY
        HTTP_PROXY: $HTTP_PROXY
    security_opt:
      - seccomp:unconfined
    ports:
      - "23:22"
    volumes:
      - type: bind
        source: $PERSISTENT_HOME_FOLDER
        target: /home/$USER_NAME
